# Generated by Django 3.1 on 2020-08-06 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100)),
                ('send_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField()),
                ('content', models.TextField()),
                ('scount', models.IntegerField(default=0)),
                ('rcount', models.IntegerField(default=0)),
                ('sender', models.ForeignKey(default='알 수 없음', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
