# Generated by Django 3.1 on 2020-08-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200807_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='renotes_r',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='renotes_s',
            field=models.IntegerField(default=0),
        ),
    ]
