# Generated by Django 3.1 on 2020-10-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20200812_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_read',
            field=models.CharField(default='읽지 않음', max_length=10),
        ),
    ]
